name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@${GITHUB_REF##*/}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: print env
        run: |
          echo "Show Default environment variables"
          echo ">> In this example <<"
          echo "HOME is :" $HOME
          echo "GITHUB_WORKFLOW is:" $GITHUB_WORKFLOW
          echo "GITHUB_RUN_ID is : "$GITHUB_RUN_ID
          echo "GITHUB_RUN_NUMBER is :" $GITHUB_RUN_NUMBER
          echo "GITHUB_ACTION is :"  $GITHUB_ACTION
          echo "GITHUB_ACTIONS is :" $GITHUB_ACTIONS
          echo "GITHUB_ACTOR is :" $GITHUB_ACTOR
          echo "GITHUB_REPOSITORY is :" $GITHUB_REPOSITORY
          echo "GITHUB_EVENT_NAME is :" $GITHUB_EVENT_NAME
          echo "GITHUB_EVENT_PATH is :" $GITHUB_EVENT_PATH
          echo "GITHUB_WORKSPACE is :"  $GITHUB_WORKSPACE
          echo "GITHUB_SHA is :"  $GITHUB_SHA
          echo "GITHUB_REF is :"  $GITHUB_REF
          echo "GITHUB_BRANCH is :" ${GITHUB_REF##*/}
          echo "GITHUB_HEAD_REF is :"  $GITHUB_HEAD_REF
          echo "GITHUB_BASE_REF is :"  $GITHUB_BASE_REF
      - name: Into Project Root
        run: cd ${GITHUB_REF##*/}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: liurongqingtest
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
